### ISSUE TITLE
Gradle Play plugin incompatible with Play 2.7

### ISSUE THREAD

**Issue by jzoran05** [playframework/play-scala-seed.g8#118]
I am not sure if I have missed some statements in the documentation but:
- The template generate project which provides both Gradle and Sbt project structure 
- When trying to use Gradle project structure (e.g. import Gradle project in Intellij) I am getting error that Play plugin specified in Gradle build config is not supported with Play 2.7 (it is template compatible with Play 2.7?)

**Comment by dwijnand** [comment]
We should drop the Gradle setup from the seed, you're right.

For more context, there are these two issues tracking Play 2.7 support in Gradle:
* https://github.com/gradle/gradle/issues/6362
* https://github.com/gradle/playframework/issues/92

**Comment by mkurz** [comment]
[Meanwhile gradle does actually support Play 2.8](https://gradle.github.io/playframework/#change_log), so if someone wants to it back here feel free to add a PR.
