### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ThomasSunKai** [playframework/play-scala-seed.g8#125]
at the beginning,i have this error,this will me back to spring boot world
![image](https://user-images.githubusercontent.com/44831813/68523451-5801a500-02f4-11ea-8e78-c9cae9783c3c.png)

**Comment by ThomasSunKai** [comment]
This will push me back....

**Comment by dwijnand** [comment]
Any ideas why it can't delete the file?  You'll need to open an issue in https://github.com/foundweekends/giter8 or https://github.com/sbt/sbt to dig into this.
