### ISSUE TITLE
Cannot see anything on screen when setting up the project

### ISSUE THREAD

**Issue by mikail-khan** [playframework/play-scala-seed.g8#127]
When I invoke, 

```
sbt new playframework/play-scala-seed.g8
```

and I get prompted for entering the project name, organisation name etc, I don't see the characters I type on the screen. This used to work before but not now. It's might be due to my terminal setup rather than the plugin. Any help would be appreciated:

![image](https://user-images.githubusercontent.com/13503259/70466877-0b101a80-1abc-11ea-9f2f-53c5a33d6247.png)

**Comment by dwijnand** [comment]
Could you describe your terminal setup?

You might have more success reporting this as an sbt issue rather than here, as it has nothing to do with this template in particular.
