### ISSUE TITLE
Template instantiation fails

### ISSUE THREAD

**Issue by stanBienaives** [playframework/play-scala-seed.g8#165]
Hello, 

I am trying to create a new play application. However the command:  `sbt new playframework/play-scala-seed.g8` fails on my Macbook M1. 

With the logs:

```sh
info] welcome to sbt 1.6.2 (Homebrew Java 18.0.1)
[info] loading global plugins from /Users/sebastienvian/.sbt/1.0/plugins
[info] set current project to new (in build file:/private/var/folders/_p/8_cj0v3502x0brrgt878v4dh0000gn/T/sbt_ee8ce529/new/)

Unexpected response status 403 fetching metadata from https://search.maven.org/solrsearch/select?q=g:%22org.scala-lang%22+AND+a:%22scala-library%22&rows=10&wt=xml&core=gav
```

Indeed the url https://search.maven.org/solarsearch send back a unauthorized 403. Not sur what this means... 
If anyone has the answer to this I would be very grateful.

**Comment by octonato** [comment]
It seems to work correctly. Could try from another machine?

**Comment by stanBienaives** [comment]
I looks like my VPN is messing things up. It works correctly when deactivated. 

Thanks for the swift response.

Have a nice day. 
I close the issue.
