### ISSUE TITLE
Warnings eviction dependencies

### ISSUE THREAD

**Issue by fpirola** [playframework/play-scala-seed.g8#38]
I noticed that play-scala-seed has warnings about eviction dependencies
[warnings-eviction.txt](https://github.com/playframework/play-scala-seed.g8/files/1292684/warnings-eviction.txt). My analisys points out that the problems seems related to only the [update from sbt 0.13.16-M1 to 0.13.16](https://github.com/playframework/play-scala-seed.g8/pull/33/files#diff-d62a1fa007b1e6288dc3c0102755b834).
Also it seems is not possible to upgrade to latest sbt available version (1.0.1) for some missing plugins (com.typesafe.play#sbt-plugin;2.6.3, org.foundweekends.giter8#sbt-giter8-scaffold;0.9.0)

How do you suggest to proceed?

**Comment by Lakret** [comment]
The same problem. Example warnings output:

```
[info] 	[SUCCESSFUL ] com.typesafe.play#play-omnidoc_2.12;2.6.11!play-omnidoc_2.12.jar (3713ms)
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* com.google.guava:guava:22.0 is selected over 19.0
[warn] 	    +- com.typesafe.play:play_2.12:2.6.11                 (depends on 22.0)
[warn] 	    +- com.google.inject:guice:4.1.0                      (depends on 19.0)
[warn] 	* com.typesafe.akka:akka-stream_2.12:2.5.8 is selected over 2.4.20
[warn] 	    +- com.typesafe.play:play-streams_2.12:2.6.11         (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-http-core_2.12:10.0.11 ()   (depends on 2.4.20)
[warn] 	* com.typesafe.akka:akka-actor_2.12:2.5.8 is selected over 2.4.20
[warn] 	    +- com.typesafe.akka:akka-slf4j_2.12:2.5.8 ()         (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-stream_2.12:2.5.8 ()        (depends on 2.5.8)
[warn] 	    +- com.typesafe.play:play_2.12:2.6.11                 (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-parsing_2.12:10.0.11 ()     (depends on 2.4.20)
[warn] Run 'evicted' to see detailed eviction warnings
```

**Comment by tooppoo** [comment]
~When same problem occured in my environment, I could resolved it by upgrading sbt version.~
~I used `brew upgrade sbt` because my environment is OS X Yosemite.~
sorry, above was misunderstanding...

**Comment by SethTisue** [comment]
closing because this is about such old versions of things — happen to reopen if someone confirms that the issue still exists
