### ISSUE TITLE
import this project in intelliJ

### ISSUE THREAD

**Issue by anopperl** [playframework/play-scala-seed.g8#43]
when i import this project in intelliJ it give me some error ....

see 
https://user-images.githubusercontent.com/16158099/33733091-956cfb20-dbae-11e7-916b-8bb4bebf3fc9.png

Error while importing SBT project: ... 
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)

**Comment by pr-lawrence** [comment]
+1

**Comment by anopperl** [comment]
hii ultimate1352, what you mean by +1

**Comment by wsargent** [comment]
The only thing I can think is that you have a very old IntelliJ IDEA version.  I would recommend getting the latest IntelliJ IDEA using the toolbox application: https://www.jetbrains.com/toolbox/app/

**Comment by wsargent** [comment]
other options -- you could have a corrupt $HOME/.ivy2 folder, and artifacts are not being resolved correctly.
